name: Attend_3

on:
    workflow_dispatch:
    schedule:
        - cron: '40 5 * * 1,2,5'
    repository_dispatch:
        types: joy

jobs:
    build:
        runs-on: macos-latest
        strategy:
            matrix:
                python-version: [3.8]

        steps:
            - name: Checkout
              run: |
                  git clone https://github.com/VidocqH/AutoAttendYuKeTang ~/AutoAttendYuKeTang
            - uses: actions/checkout@v2
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            - name: '运行自动签到'
              run: |
                  python ./src/startup.py
              env:
                  USER_INFO: ${{ secrets.USER_INFO }}
                  PUSH_KEY: ${{ secrets.PUSH_KEY }}
                  BARK_ID: ${{ secrets.BARK_ID }}
